### ISSUE TITLE
 highlight correctly port number

### ISSUE THREAD

**Issue by sSiDs** [Tes3awy/Cisco-IOS-XE-NotepadPlusPlus-Syntax-Highlight#2]
good day!
what need to be configured in file to highlight correctly port numbers, ie 1/1 or 1/1/2...etc

**Comment by sSiDs** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/20465150/153267882-1a98eae2-b4b3-4524-8708-2e6ceb8fa257.png)

**Comment by Tes3awy** [comment]
A white space after `GigabitEthernet` should solve it, as 1 is considered part of the word. If you double click `GigabitEthernet`, `GigabitEthernet1` is highlighted. Special characters like slashes and dashes are separators that indicate the end of a word.

White spaces are still a valid option in copy/paste to network devices. It's something related to how Cisco shows the running configuration that port speed is glued to the device number

![image](https://user-images.githubusercontent.com/11368432/153403790-c06c04fb-252d-418e-89d7-e05601f9d8a5.png)
